name: Build and publish all Docker images

env:
  CORE_API_DOCKERFILE_PATH: "OnlineShopAPI/OnlineShopAPI/Dockerfile"

on:
  workflow_dispatch:

jobs:
  Docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Log in Docker
        run: docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASS }}"
      - name: Build the Docker image
        run: docker build . --file ${{ env.CORE_API_DOCKERFILE_PATH }} --tag "${{ secrets.DOCKER_USERNAME }}"/core-api:latest
      - name: Docker push
        run: docker push "${{ secrets.DOCKER_USERNAME }}"/core-api
